# Generated by Django 3.2.4 on 2022-11-03 07:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='menus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.CharField(max_length=100, verbose_name='名称')),
                ('place', models.CharField(default='', max_length=100, verbose_name='地点')),
                ('upload_time', models.DateTimeField(default=datetime.datetime(2022, 11, 3, 15, 11, 17, 192736), verbose_name='上传时间')),
                ('upload_user', models.CharField(default='', max_length=100, verbose_name='上传人')),
                ('picture', models.CharField(max_length=100, verbose_name='图片')),
                ('price', models.DecimalField(decimal_places=2, max_digits=64, verbose_name='价格')),
            ],
            options={
                'verbose_name': '菜单',
                'verbose_name_plural': '菜单',
                'db_table': 'menus',
            },
        ),
        migrations.CreateModel(
            name='run_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eat_time', models.DateTimeField(default=datetime.datetime(2022, 11, 3, 15, 11, 17, 193707), verbose_name='时间')),
                ('user_mark', models.CharField(max_length=100, verbose_name='用户标识')),
                ('is_login', models.CharField(max_length=100, verbose_name='是否登陆')),
                ('have_eat', models.CharField(max_length=100, verbose_name='选择结果')),
            ],
            options={
                'verbose_name': '运行日志',
                'verbose_name_plural': '运行日志',
                'db_table': 'run_log',
            },
        ),
    ]
