# Generated by Django 5.0.1 on 2024-01-05 07:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eat_what", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menus",
            name="upload_time",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 1, 5, 15, 39, 42, 994352),
                verbose_name="上传时间",
            ),
        ),
        migrations.AlterField(
            model_name="run_log",
            name="eat_time",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 1, 5, 15, 39, 42, 994352),
                verbose_name="时间",
            ),
        ),
    ]
